<a href="https://colab.research.google.com/github/snikhil17/Deep-Learning/blob/main/3.%20Sigmoid_Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Class for Sigmoid Neuron

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
class SigmoidNeuron:

  def __init__(self):
    self.w = None
    self.b = None
  
  def perceptron(self, x):
    return np.dot(x, self.w.T) + self.b

  def sigmoid(self, x):
    return 1.0 / (1.0 + np.exp(-x))

  def grad_w(self, x, y):
    y_pred = self.sigmoid(self.perceptron(x))
    return (y_pred - y) * y_pred *  (1-y_pred) * x

  def grad_b(self, x, y):
    y_pred = self.sigmoid(self.perceptron(x))
    return (y_pred - y) * y_pred *  (1-y_pred)

  def fit(self, X, Y, epochs = 1, learning_rate = 1, initialise = True):
    # Initialise w and b
    if initialise:
      self.w = np.random.randn(1,X.shape[1])
      self.b = 0

    for i in range(epochs):
      dw = 0
      db = 0
      for x,y in zip(X, Y):
        dw += self.grad_w(x,y)
        db += self.grad_b(x,y)

      self.w -= learning_rate * dw
      self.b -= learning_rate * db

# Fit for toy Data

In [11]:
X = np.asarray([[2.5,2.5], [4,-1], [1,4], [3,1.25], [2,4], [1,5]])
Y = [1,1,1,0,0,0]


In [12]:
sn = SigmoidNeuron()
sn.fit(X, Y, 1, 0.25, True)

In [15]:
sn.fit(X, Y, 1, 0.25, True)
for i in range(10):
  print(sn.w, sn.b)
  sn.fit(X, Y, 1, 0.25, False)

[[1.62488607 0.56441363]] [-0.00430747]
[[1.61734345 0.54543131]] [-0.00898302]
[[1.60916808 0.52452282]] [-0.01409593]
[[1.60023423 0.50127893]] [-0.01973649]
[[1.59037489 0.47515152]] [-0.02602515]
[[1.57936202 0.44538582]] [-0.03312704]
[[1.56687383 0.41090838]] [-0.04127597]
[[1.55243819 0.37013255]] [-0.05081578]
[[1.53532893 0.32060433]] [-0.06227552]
[[1.51436501 0.25832498]] [-0.07651232]
