<a href="https://colab.research.google.com/github/snikhil17/Deep-Learning/blob/main/TensorFlow_1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TF Syntax Basics**

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
print(tf.__version__)

2.6.0


In [3]:
hello = tf.constant("Hello ")


In [4]:
world = tf.constant("world")


In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
  result = sess.run(hello+world)

result
# result = hello+world
# tf.print(result)

b'Hello world'

In [8]:
a = tf.constant(10)

In [9]:
b = tf.constant(20)

In [10]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
  result  = sess.run(a+b)

result

30

In [13]:
const = tf.constant(10)

In [14]:
fill_mat = tf.fill((4,4),10)

In [15]:
myzeros = tf.zeros((4,4))

In [16]:
myones = tf.ones((4,4))

In [17]:
myrandn = tf.random_normal((4,4), mean = 0, stddev=1.0)

In [18]:
myrandu = tf.random_uniform((4,4), minval = 0, maxval=1)

In [19]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [20]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [21]:
"""Interactive session Creates session for all the operations. Good for Jupyter notebooks"""
sess = tf.InteractiveSession()

In [22]:
for op in my_ops:
  print(sess.run(op), '\n')

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[ 0.29622248  0.9726476  -1.0100683  -0.6107657 ]
 [-0.39844006  1.7451514   1.7232699   0.2984426 ]
 [-0.9610435  -0.17117737 -0.16976157 -0.6867104 ]
 [ 2.5186636   0.3885328  -0.22904499 -0.58194935]] 

[[0.70931065 0.8936484  0.6712568  0.30970693]
 [0.80798864 0.3085605  0.8861493  0.8241303 ]
 [0.94754136 0.6955093  0.8753638  0.6422863 ]
 [0.12617242 0.42434967 0.5707756  0.92917013]] 



In [23]:
a = tf.constant([ [1,2],
                  [3,4]])

In [24]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [25]:
b = tf.constant( [ [10], [100] ] )

In [26]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [27]:
result = tf.matmul(a,b)

In [28]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [29]:
result.eval()

array([[210],
       [430]], dtype=int32)

# **TF Graphs**

In [30]:
n1 = tf.constant(1)

In [31]:
n2 = tf.constant(2)

In [32]:
n3 = n1+n2

In [33]:
with tf.Session() as sess:
  result = sess.run(n3)

In [34]:
result

3

In [35]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


In [36]:
print(tf.get_default_graph())

In [37]:
g = tf.Graph()

In [38]:
print(g)

In [39]:
graph_one = tf.get_default_graph()
graph_one

In [40]:
graph_two = tf.Graph()
graph_two

In [41]:
"""Setting Graph 2 as default graph"""
with graph_two.as_default():                   # Setting Graph 2 as default graph
  print(graph_two is tf.get_default_graph())   # checking if graph_2 is already default graph


True


In [42]:
"""Outside with statement graph_two is not a default graph"""
print(graph_two is tf.get_default_graph())

False


# **Variables and Placeholders**

In [43]:
 sess= tf.InteractiveSession()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1766: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [44]:
my_tensor = tf.random_uniform((4,4), 0,1)

In [45]:
my_tensor

<tf.Tensor 'random_uniform_1/RandomUniform:0' shape=(4, 4) dtype=float32>

In [46]:
my_var = tf.Variable(initial_value= my_tensor)
my_var

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>

**If you run the variable without initializing then we get the error.**

In [47]:
sess.run(my_var)

FailedPreconditionError: ignored

**Initializing all the variables**

In [48]:
init = tf.global_variables_initializer()

In [49]:
sess.run(init)

In [50]:
sess.run(my_var)

array([[0.4185319 , 0.83617127, 0.18584931, 0.44334662],
       [0.34373713, 0.052719  , 0.85412264, 0.93996763],
       [0.07185221, 0.9346918 , 0.23455119, 0.82219756],
       [0.37630606, 0.49289405, 0.37269068, 0.6309774 ]], dtype=float32)

## **Placeholders**

In [51]:
ph = tf.placeholder(tf.float32, shape = (None, 5))
# None here means that we can put in the batches we will be creating here. Batches from GD  